workspace:
  base: /go
  path: src/github.com/karantin2020/qlog

pipeline:
  test1.9:
    group: tests
    image: golang:1.9.2-alpine3.6
    commands:
      - go test -v

  test1.10:
    group: tests
    image: golang:1.10-alpine3.7
    commands:
      - go test -v

  bench1.9:
    image: golang:1.9.2-alpine3.6
    commands:
      - go test -benchmem  -bench=. -benchtime 5s

  bench1.10:
    image: golang:1.10-alpine3.7
    commands:
      - go test -benchmem  -bench=. -benchtime 5s
